version: '3.3'

services:
  mysql:
    image: mysql:5.7
      volumes:
      - mysql_data:/var/lib/mysql
        ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sql
      MYSQL_USER: mani
      MYSQL_PASSWORD: sql


volumes:
  mysql_data: {}
